# Generated by Django 2.2 on 2019-06-05 04:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_auto_20190605_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 4, 9, 33, 488845, tzinfo=utc)),
        ),
    ]
